# _quarto.yml

project:
  type: website

website:
  title: "RetailFlow"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: consultant.qmd
        text: "Consultant Dashboard"
      - text: "Company"
        menu:
          - href: company/overview.qmd
            text: "Overview"
          - href: company/team.qmd
            text: "Team"
      - text: "Project"
        menu:
          - href: project/charter.qmd
            text: "Project Charter"
          - href: project/timeline.qmd
            text: "Timeline"
      - text: "Resources"
        menu:
          - href: resources/scenarios.qmd
            text: "Scenarios"
          - href: resources/documents.qmd
            text: "Documents"
      - href: contact.qmd
        text: "Contact"
      - href: docs/retailflow_legal_disclaimer.md
        text: "Education Site"
  sidebar:
    - title: "Company"
      contents:
        - company/overview.qmd
        - company/team.qmd
    - title: "Project"
      contents:
        - project/charter.qmd
        - project/timeline.qmd
    - title: "Resources"
      contents:
        - resources/scenarios.qmd
        - resources/documents.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    include-after-body:
      - text: |
          <footer class="footer py-4 bg-dark text-light">
            <div class="container">
              <div class="row">
                <div class="col-md-4">
                  <h5>RetailFlow</h5>
                  <p>Australia's fastest-growing retail destination, connecting millions of customers with the products they love.</p>
                  <div class="social-links">
                    <a href="#" class="text-light me-3"><i class="bi bi-facebook"></i></a>
                    <a href="#" class="text-light me-3"><i class="bi bi-twitter"></i></a>
                    <a href="#" class="text-light me-3"><i class="bi bi-instagram"></i></a>
                    <a href="#" class="text-light"><i class="bi bi-linkedin"></i></a>
                  </div>
                </div>
                
                <div class="col-md-2">
                  <h6>Shop</h6>
                  <ul class="list-unstyled">
                    <li><a href="#" class="text-light text-decoration-none">New Arrivals</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Best Sellers</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Sale Items</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Gift Cards</a></li>
                  </ul>
                </div>
                
                <div class="col-md-2">
                  <h6>Customer Service</h6>
                  <ul class="list-unstyled">
                    <li><a href="contact.html" class="text-light text-decoration-none">Contact Us</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Shipping Info</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Returns</a></li>
                    <li><a href="#" class="text-light text-decoration-none">FAQ</a></li>
                  </ul>
                </div>
                
                <div class="col-md-2">
                  <h6>About</h6>
                  <ul class="list-unstyled">
                    <li><a href="company/overview.html" class="text-light text-decoration-none">Our Story</a></li>
                    <li><a href="company/team.html" class="text-light text-decoration-none">Leadership</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Careers</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Press</a></li>
                  </ul>
                </div>
                
                <div class="col-md-2">
                  <h6>Legal</h6>
                  <ul class="list-unstyled">
                    <li><a href="#" class="text-light text-decoration-none">Privacy Policy</a></li>
                    <li><a href="#" class="text-light text-decoration-none">Terms of Service</a></li>
                    <li><a href="docs/retailflow_legal_disclaimer.html" class="text-light text-decoration-none">Education Site</a></li>
                  </ul>
                </div>
              </div>
              
              <hr class="my-4 border-secondary">
              
              <div class="row align-items-center">
                <div class="col-md-6">
                  <p class="mb-0">&copy; 2024 RetailFlow. All rights reserved.</p>
                </div>
                <div class="col-md-6 text-md-end">
                  <p class="mb-0">
                    <small class="text-muted">ABN: 123 456 789 000 | ACN: 123 456 789</small>
                  </p>
                </div>
              </div>
            </div>
          </footer>
          <style>
          .footer {
            margin-top: 3rem;
          }
          
          .footer a:hover {
            color: var(--retailflow-accent) !important;
          }
          
          .social-links a {
            font-size: 1.2rem;
            transition: color 0.2s;
          }
          
          .social-links a:hover {
            color: var(--retailflow-accent) !important;
          }
          </style>

